/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AuthForm: typeof import('./src/components/AuthForm.vue')['default']
    Button: typeof import('primevue/button')['default']
    CreateEvent: typeof import('./src/components/forms/CreateEvent.vue')['default']
    DatePicker: typeof import('primevue/datepicker')['default']
    EventForm: typeof import('./src/components/EventForm.vue')['default']
    FloatLabel: typeof import('primevue/floatlabel')['default']
    Form: typeof import('@primevue/forms/form')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Message: typeof import('primevue/message')['default']
    PageDescription: typeof import('./src/components/PageDescription.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    Toast: typeof import('primevue/toast')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
